name: MattMitchell
favicon: null
layout_spectrum: 0.39032814814709127
typography_spectrum: 0.6266983090899885
title: Matt Mitchell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.39525181730277836
  lightness: 0.5013108416460454
  saturation: 0.4936030462849885
  rhythmicContrast: 0.5892119545023888
purpose: []
